import type {
  Organisation, WaitlistEntry, User, AuditEvent,
  Invitation, SSOConfig, PlatformStats, PlanFeature,
} from './types'
import { getDefaultPermissions } from './permissions'

/* ── Feature sets by tier ─────────────────────────────────────────────────── */

const STARTER_FEATURES: PlanFeature[] = ['audit_log']

const PROFESSIONAL_FEATURES: PlanFeature[] = [
  'api_access', 'advanced_analytics', 'custom_sla',
  'audit_log', 'bulk_import', 'webhooks',
]

const ENTERPRISE_FEATURES: PlanFeature[] = [
  'sso_microsoft', 'sso_google', 'api_access', 'advanced_analytics',
  'custom_sla', 'audit_log', 'priority_support', 'white_label',
  'bulk_import', 'webhooks',
]

/* ── Organisations ────────────────────────────────────────────────────────── */

export const ORGANISATIONS: Organisation[] = [
  {
    id: 'org_001',
    name: 'Shell Nigeria',
    slug: 'shell-nigeria',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'active',
    subscription: {
      tier: 'enterprise',
      status: 'active',
      seats: 48,
      seatsUsed: 32,
      monthlyPrice: 2499,
      billingCycleStart: '2026-01-01',
      billingCycleEnd: '2026-12-31',
      features: ENTERPRISE_FEATURES,
    },
    microsoftTenantId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    adminEmail: 'emeka.nwosu@shellnigeria.com',
    createdAt: '2024-03-15T09:00:00Z',
    onboardedAt: '2024-03-20T14:00:00Z',
    memberCount: 32,
    activeWorkOrders: 47,
    healthScore: 92,
  },
  {
    id: 'org_002',
    name: 'Seplat Energy',
    slug: 'seplat-energy',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'active',
    subscription: {
      tier: 'professional',
      status: 'active',
      seats: 20,
      seatsUsed: 14,
      monthlyPrice: 799,
      billingCycleStart: '2026-06-01',
      billingCycleEnd: '2026-06-30',
      features: PROFESSIONAL_FEATURES,
    },
    microsoftTenantId: 'b2c3d4e5-f6a7-8901-bcde-f01234567891',
    adminEmail: 'olumide.akinwunmi@seplatpetroleum.com',
    createdAt: '2024-08-10T10:30:00Z',
    onboardedAt: '2024-08-15T08:00:00Z',
    memberCount: 14,
    activeWorkOrders: 23,
    healthScore: 88,
  },
  {
    id: 'org_003',
    name: 'Oando PLC',
    slug: 'oando-plc',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'active',
    subscription: {
      tier: 'professional',
      status: 'active',
      seats: 16,
      seatsUsed: 12,
      monthlyPrice: 649,
      billingCycleStart: '2026-05-15',
      billingCycleEnd: '2026-06-14',
      features: PROFESSIONAL_FEATURES,
    },
    adminEmail: 'kunle.adegoke@oandoplc.com',
    createdAt: '2025-01-20T11:00:00Z',
    onboardedAt: '2025-01-25T09:30:00Z',
    memberCount: 12,
    activeWorkOrders: 18,
    healthScore: 79,
  },
  {
    id: 'org_004',
    name: 'Lekoil Nigeria',
    slug: 'lekoil-nigeria',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'active',
    subscription: {
      tier: 'starter',
      status: 'active',
      seats: 6,
      seatsUsed: 4,
      monthlyPrice: 199,
      billingCycleStart: '2026-06-10',
      billingCycleEnd: '2026-07-09',
      features: STARTER_FEATURES,
    },
    adminEmail: 'emeka.obi@lekoil.com.ng',
    createdAt: '2025-03-05T14:00:00Z',
    onboardedAt: '2025-03-08T10:00:00Z',
    memberCount: 4,
    activeWorkOrders: 6,
    healthScore: 71,
  },
  {
    id: 'org_005',
    name: 'Aiteo Eastern E&P',
    slug: 'aiteo-eastern',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'onboarding',
    subscription: {
      tier: 'professional',
      status: 'active',
      seats: 12,
      seatsUsed: 3,
      monthlyPrice: 499,
      billingCycleStart: '2026-06-20',
      billingCycleEnd: '2026-07-19',
      features: PROFESSIONAL_FEATURES,
    },
    adminEmail: 'peter.abah@aiteo.com.ng',
    createdAt: '2026-06-20T08:00:00Z',
    memberCount: 3,
    activeWorkOrders: 2,
    healthScore: 55,
  },
  {
    id: 'org_006',
    name: 'Conoil',
    slug: 'conoil',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'waitlist',
    subscription: {
      tier: 'starter',
      status: 'trialing',
      seats: 8,
      seatsUsed: 1,
      monthlyPrice: 199,
      billingCycleStart: '2026-06-27',
      billingCycleEnd: '2026-07-26',
      trialEndsAt: '2026-07-26T00:00:00Z',
      features: STARTER_FEATURES,
    },
    adminEmail: 'ahmed.tijani@conoil.com.ng',
    createdAt: '2026-06-25T15:00:00Z',
    memberCount: 1,
    activeWorkOrders: 0,
    healthScore: 30,
  },
  {
    id: 'org_007',
    name: 'Waltersmith Petroman',
    slug: 'waltersmith-petroman',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'suspended',
    subscription: {
      tier: 'starter',
      status: 'past_due',
      seats: 5,
      seatsUsed: 3,
      monthlyPrice: 199,
      billingCycleStart: '2026-05-01',
      billingCycleEnd: '2026-05-31',
      features: STARTER_FEATURES,
    },
    adminEmail: 'joseph.walters@waltersmith.ng',
    createdAt: '2025-09-12T10:00:00Z',
    onboardedAt: '2025-09-15T09:00:00Z',
    memberCount: 3,
    activeWorkOrders: 0,
    healthScore: 12,
  },
  {
    id: 'org_008',
    name: 'Ardova Petroleum',
    slug: 'ardova-petroleum',
    industry: 'Oil & Gas',
    country: 'Nigeria',
    timezone: 'Africa/Lagos',
    status: 'active',
    subscription: {
      tier: 'professional',
      status: 'trialing',
      seats: 12,
      seatsUsed: 5,
      monthlyPrice: 499,
      billingCycleStart: '2026-06-15',
      billingCycleEnd: '2026-07-14',
      trialEndsAt: '2026-07-14T00:00:00Z',
      features: PROFESSIONAL_FEATURES,
    },
    adminEmail: 'tokunbo.aromolaran@ardovapetroleum.com',
    createdAt: '2026-06-15T11:00:00Z',
    memberCount: 5,
    activeWorkOrders: 8,
    healthScore: 62,
  },
]

/* ── Waitlist ─────────────────────────────────────────────────────────────── */

export const WAITLIST: WaitlistEntry[] = [
  {
    id: 'wl_001',
    companyName: 'Conoil',
    contactName: 'Ahmed Tijani',
    contactEmail: 'ahmed.tijani@conoil.com.ng',
    contactPhone: '+234 802 345 6789',
    industry: 'Oil & Gas',
    estimatedTeamSize: 8,
    useCaseDescription: 'Equipment tracking for three onshore rigs in the Niger Delta. Currently managing via spreadsheets — experiencing frequent SLA breaches due to poor handoff visibility.',
    status: 'approved',
    priority: 'high',
    submittedAt: '2026-06-18T10:00:00Z',
    reviewedAt: '2026-06-25T14:00:00Z',
    reviewedBy: 'user_000',
    notes: 'Strong fit. Decision maker on the call. Fast approval.',
    convertedToOrgId: 'org_006',
  },
  {
    id: 'wl_002',
    companyName: 'Brass LNG Ltd',
    contactName: 'Nnamdi Okoye',
    contactEmail: 'nnamdi.okoye@brasslng.com',
    contactPhone: '+234 803 456 7890',
    industry: 'Oil & Gas',
    estimatedTeamSize: 35,
    useCaseDescription: 'LNG terminal equipment lifecycle management. We operate rotating equipment across 4 terminals and need better SLA tracking for maintenance work orders.',
    status: 'pending',
    priority: 'high',
    submittedAt: '2026-06-24T09:30:00Z',
  },
  {
    id: 'wl_003',
    companyName: 'NPDC (Nigerian Petroleum Development Company)',
    contactName: 'Chinyere Eze',
    contactEmail: 'chinyere.eze@npdc.ng',
    industry: 'Oil & Gas',
    estimatedTeamSize: 120,
    useCaseDescription: 'National operator seeking to standardise equipment requisition and dispatch across 22 joint venture blocks. Complex QAQC requirements due to government audit obligations.',
    status: 'pending',
    priority: 'high',
    submittedAt: '2026-06-22T11:00:00Z',
  },
  {
    id: 'wl_004',
    companyName: 'Sahara Group',
    contactName: 'Biodun Fadahunsi',
    contactEmail: 'biodun.fadahunsi@sahara-group.com',
    contactPhone: '+234 704 567 8901',
    industry: 'Oil & Gas',
    estimatedTeamSize: 50,
    useCaseDescription: 'Midstream energy company needing equipment tracking across storage terminals and pipeline operations.',
    status: 'approved',
    priority: 'medium',
    submittedAt: '2026-06-10T14:00:00Z',
    reviewedAt: '2026-06-16T10:00:00Z',
    reviewedBy: 'user_000',
    notes: 'Good potential. Awaiting procurement approval from their end.',
  },
  {
    id: 'wl_005',
    companyName: 'Matrix Energy Group',
    contactName: 'Uche Orji',
    contactEmail: 'uche.orji@matrixenergy.ng',
    industry: 'Oil & Gas',
    estimatedTeamSize: 28,
    useCaseDescription: 'Petroleum distribution company looking to track specialist equipment across depots. Urgent — Q3 audit requirement.',
    status: 'pending',
    priority: 'high',
    submittedAt: '2026-06-25T16:00:00Z',
  },
  {
    id: 'wl_006',
    companyName: 'Forte Oil',
    contactName: 'Dauda Lawal',
    contactEmail: 'dauda.lawal@forteoilplc.com',
    industry: 'Oil & Gas',
    estimatedTeamSize: 22,
    useCaseDescription: 'Equipment management for upstream and downstream operations. Interested in the warehouse module specifically.',
    status: 'converted',
    priority: 'medium',
    submittedAt: '2025-11-05T10:00:00Z',
    reviewedAt: '2025-11-10T09:00:00Z',
    reviewedBy: 'user_000',
    convertedToOrgId: 'org_009',
  },
  {
    id: 'wl_007',
    companyName: 'TotalEnergies Nigeria',
    contactName: 'Femi Adeleke',
    contactEmail: 'femi.adeleke@totalenergies.ng',
    contactPhone: '+234 808 123 4567',
    industry: 'Oil & Gas',
    estimatedTeamSize: 90,
    useCaseDescription: 'Enterprise-scale equipment lifecycle management across deepwater blocks OML 102 and OML 130. Requires Microsoft SSO, custom SLA thresholds, and executive reporting.',
    status: 'pending',
    priority: 'high',
    submittedAt: '2026-06-26T08:00:00Z',
  },
  {
    id: 'wl_008',
    companyName: 'Chevron Nigeria',
    contactName: 'Osas Idemudia',
    contactEmail: 'osas.idemudia@chevron.com',
    industry: 'Oil & Gas',
    estimatedTeamSize: 75,
    useCaseDescription: 'Tracking drilling equipment across the Escravos gas plant and offshore platforms. Needs robust audit trail for HSE compliance.',
    status: 'approved',
    priority: 'high',
    submittedAt: '2026-06-14T13:00:00Z',
    reviewedAt: '2026-06-20T11:00:00Z',
    reviewedBy: 'user_000',
    notes: 'Enterprise candidate. On hold pending legal review of data residency requirements.',
  },
  {
    id: 'wl_009',
    companyName: 'Mobil Nigeria Upstream',
    contactName: 'Ekene Obiechina',
    contactEmail: 'ekene.obiechina@mobil.com.ng',
    industry: 'Oil & Gas',
    estimatedTeamSize: 40,
    useCaseDescription: 'Upstream equipment tracking for QIT terminal operations. Interested in QAQC inspection module.',
    status: 'pending',
    priority: 'medium',
    submittedAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'wl_010',
    companyName: 'Pan Ocean Oil',
    contactName: 'Tope Adeniyi',
    contactEmail: 'tope.adeniyi@panoceanoil.com',
    industry: 'Oil & Gas',
    estimatedTeamSize: 18,
    useCaseDescription: 'We operate OPL 98 and need better coordination between warehouse and dispatch teams for subsea equipment.',
    status: 'pending',
    priority: 'medium',
    submittedAt: '2026-06-23T15:30:00Z',
  },
  {
    id: 'wl_011',
    companyName: 'Dubri Oil Company',
    contactName: 'Samson Okeke',
    contactEmail: 'samson.okeke@dubrioil.com',
    industry: 'Oil & Gas',
    estimatedTeamSize: 4,
    useCaseDescription: 'Small oil company looking for equipment tracking.',
    status: 'rejected',
    priority: 'low',
    submittedAt: '2026-05-30T12:00:00Z',
    reviewedAt: '2026-06-04T10:00:00Z',
    reviewedBy: 'user_000',
    notes: 'Too small for current product offering. Team of 4 does not meet minimum viable seat requirement.',
  },
  {
    id: 'wl_012',
    companyName: 'Gulf Drilling International',
    contactName: 'Ibrahim Hassan',
    contactEmail: 'ibrahim.hassan@gulf-drilling.com',
    industry: 'Oil & Gas',
    estimatedTeamSize: 30,
    useCaseDescription: 'International operator seeking EquipTrack for Nigerian operations.',
    status: 'rejected',
    priority: 'low',
    submittedAt: '2026-05-20T09:00:00Z',
    reviewedAt: '2026-05-28T14:00:00Z',
    reviewedBy: 'user_000',
    notes: 'Operations not based in Nigeria. Outside current geographic scope.',
  },
  {
    id: 'wl_013',
    companyName: 'Allied Energy Resources',
    contactName: 'Babatunde Awogboro',
    contactEmail: 'babatunde.awogboro@alliedresources.ng',
    industry: 'Oil & Gas',
    estimatedTeamSize: 15,
    useCaseDescription: 'Mid-size E&P company, two onshore blocks in Ondo State.',
    status: 'converted',
    priority: 'medium',
    submittedAt: '2025-09-15T10:00:00Z',
    reviewedAt: '2025-09-22T11:00:00Z',
    reviewedBy: 'user_000',
    convertedToOrgId: 'org_010',
  },
  {
    id: 'wl_014',
    companyName: 'Oriental Energy Resources',
    contactName: 'Chukwudi Eze',
    contactEmail: 'chukwudi.eze@orientalenergy.com',
    industry: 'Oil & Gas',
    estimatedTeamSize: 25,
    useCaseDescription: 'Operator of OML 115 looking for equipment lifecycle management across two rig sites.',
    status: 'converted',
    priority: 'medium',
    submittedAt: '2025-07-08T09:00:00Z',
    reviewedAt: '2025-07-15T10:30:00Z',
    reviewedBy: 'user_000',
    convertedToOrgId: 'org_011',
  },
  {
    id: 'wl_015',
    companyName: 'Niger Delta Petroleum',
    contactName: 'Azuka Nwosu',
    contactEmail: 'azuka.nwosu@ndpetroleum.ng',
    industry: 'Oil & Gas',
    estimatedTeamSize: 6,
    useCaseDescription: 'Looking for an affordable equipment tracking solution for a small operation.',
    status: 'pending',
    priority: 'low',
    submittedAt: '2026-06-26T17:00:00Z',
  },
]

/* ── Users ────────────────────────────────────────────────────────────────── */

export const USERS: User[] = [
  // ── Sysadmin ─────────────────────────────────────────────────────────────
  {
    id: 'user_000',
    orgId: null,
    email: 'aminu.garba@equiptrack.io',
    displayName: 'Aminu Garba',
    role: 'sysadmin',
    status: 'active',
    authProvider: 'email',
    jobTitle: 'Platform Administrator',
    createdAt: '2024-01-01T00:00:00Z',
    lastActiveAt: '2026-06-27T08:15:00Z',
    permissions: getDefaultPermissions('sysadmin'),
  },

  // ── Shell Nigeria ─────────────────────────────────────────────────────────
  {
    id: 'user_001',
    orgId: 'org_001',
    email: 'emeka.nwosu@shellnigeria.com',
    displayName: 'Chukwuemeka Nwosu',
    role: 'org_admin',
    status: 'active',
    authProvider: 'microsoft_sso',
    microsoftId: 'ms-nwosu-001',
    department: 'Management',
    jobTitle: 'Operations Manager',
    phoneNumber: '+234 802 111 2222',
    createdAt: '2024-03-20T14:00:00Z',
    lastActiveAt: '2026-06-27T07:45:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_002',
    orgId: 'org_001',
    email: 'fatima.musa@shellnigeria.com',
    displayName: 'Fatima Musa',
    role: 'exec_viewer',
    status: 'active',
    authProvider: 'microsoft_sso',
    microsoftId: 'ms-musa-002',
    department: 'Executive',
    jobTitle: 'Director, Field Operations',
    createdAt: '2024-03-21T09:00:00Z',
    lastActiveAt: '2026-06-26T16:30:00Z',
    invitedBy: 'user_001',
    permissions: getDefaultPermissions('exec_viewer'),
  },
  {
    id: 'user_003',
    orgId: 'org_001',
    email: 'babatunde.olatunji@shellnigeria.com',
    displayName: 'Babatunde Olatunji',
    role: 'wh_supervisor',
    status: 'active',
    authProvider: 'microsoft_sso',
    microsoftId: 'ms-olatunji-003',
    department: 'Warehouse',
    jobTitle: 'Warehouse Supervisor',
    phoneNumber: '+234 803 222 3333',
    createdAt: '2024-03-22T10:00:00Z',
    lastActiveAt: '2026-06-27T06:00:00Z',
    invitedBy: 'user_001',
    permissions: getDefaultPermissions('wh_supervisor'),
  },
  {
    id: 'user_004',
    orgId: 'org_001',
    email: 'ngozi.adeyemi@shellnigeria.com',
    displayName: 'Ngozi Adeyemi',
    role: 'dsp_supervisor',
    status: 'active',
    authProvider: 'email',
    department: 'Dispatch',
    jobTitle: 'Dispatch Supervisor',
    phoneNumber: '+234 804 333 4444',
    createdAt: '2024-03-22T11:00:00Z',
    lastActiveAt: '2026-06-27T06:30:00Z',
    invitedBy: 'user_001',
    permissions: getDefaultPermissions('dsp_supervisor'),
  },
  {
    id: 'user_005',
    orgId: 'org_001',
    email: 'sule.ibrahim@shellnigeria.com',
    displayName: 'Sule Ibrahim',
    role: 'qaqc_officer',
    status: 'active',
    authProvider: 'email',
    department: 'QA/QC',
    jobTitle: 'Quality Assurance Officer',
    createdAt: '2024-04-01T09:00:00Z',
    lastActiveAt: '2026-06-26T14:00:00Z',
    invitedBy: 'user_001',
    permissions: getDefaultPermissions('qaqc_officer'),
  },
  {
    id: 'user_006',
    orgId: 'org_001',
    email: 'adaeze.okafor@shellnigeria.com',
    displayName: 'Adaeze Okafor',
    role: 'wh_personnel',
    status: 'active',
    authProvider: 'microsoft_sso',
    microsoftId: 'ms-okafor-006',
    department: 'Warehouse',
    jobTitle: 'Warehouse Technician',
    createdAt: '2024-04-05T08:00:00Z',
    lastActiveAt: '2026-06-27T07:00:00Z',
    invitedBy: 'user_003',
    permissions: getDefaultPermissions('wh_personnel'),
  },
  {
    id: 'user_007',
    orgId: 'org_001',
    email: 'yetunde.afolabi@shellnigeria.com',
    displayName: 'Yetunde Afolabi',
    role: 'dsp_personnel',
    status: 'active',
    authProvider: 'email',
    department: 'Dispatch',
    jobTitle: 'Dispatch Operative',
    createdAt: '2024-04-08T09:00:00Z',
    lastActiveAt: '2026-06-27T06:45:00Z',
    invitedBy: 'user_004',
    permissions: getDefaultPermissions('dsp_personnel'),
  },

  // ── Seplat Energy ─────────────────────────────────────────────────────────
  {
    id: 'user_008',
    orgId: 'org_002',
    email: 'olumide.akinwunmi@seplatpetroleum.com',
    displayName: 'Olumide Akinwunmi',
    role: 'org_admin',
    status: 'active',
    authProvider: 'email',
    department: 'Management',
    jobTitle: 'HSE & Logistics Manager',
    phoneNumber: '+234 805 444 5555',
    createdAt: '2024-08-15T08:00:00Z',
    lastActiveAt: '2026-06-27T07:20:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_009',
    orgId: 'org_002',
    email: 'chisom.eze@seplatpetroleum.com',
    displayName: 'Chisom Eze',
    role: 'requester',
    status: 'active',
    authProvider: 'email',
    department: 'Engineering',
    jobTitle: 'Drilling Engineer',
    createdAt: '2024-08-20T09:00:00Z',
    lastActiveAt: '2026-06-26T15:00:00Z',
    invitedBy: 'user_008',
    permissions: getDefaultPermissions('requester'),
  },
  {
    id: 'user_010',
    orgId: 'org_002',
    email: 'tunde.bakare@seplatpetroleum.com',
    displayName: 'Tunde Bakare',
    role: 'wh_supervisor',
    status: 'active',
    authProvider: 'email',
    department: 'Warehouse',
    jobTitle: 'Stores & Logistics Supervisor',
    createdAt: '2024-08-22T10:00:00Z',
    lastActiveAt: '2026-06-27T06:15:00Z',
    invitedBy: 'user_008',
    permissions: getDefaultPermissions('wh_supervisor'),
  },
  {
    id: 'user_011',
    orgId: 'org_002',
    email: 'hadiza.usman@seplatpetroleum.com',
    displayName: 'Hadiza Usman',
    role: 'qaqc_officer',
    status: 'active',
    authProvider: 'email',
    department: 'QA/QC',
    jobTitle: 'QA Inspector',
    createdAt: '2024-09-01T09:00:00Z',
    lastActiveAt: '2026-06-25T11:30:00Z',
    invitedBy: 'user_008',
    permissions: getDefaultPermissions('qaqc_officer'),
  },

  // ── Oando PLC ─────────────────────────────────────────────────────────────
  {
    id: 'user_012',
    orgId: 'org_003',
    email: 'kunle.adegoke@oandoplc.com',
    displayName: 'Kunle Adegoke',
    role: 'org_admin',
    status: 'active',
    authProvider: 'email',
    department: 'Operations',
    jobTitle: 'Operations Superintendent',
    createdAt: '2025-01-25T09:30:00Z',
    lastActiveAt: '2026-06-27T07:55:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_013',
    orgId: 'org_003',
    email: 'chidi.nwosu@oandoplc.com',
    displayName: 'Chidi Nwosu',
    role: 'requester',
    status: 'active',
    authProvider: 'email',
    department: 'Engineering',
    jobTitle: 'Field Engineer',
    createdAt: '2025-02-01T08:00:00Z',
    lastActiveAt: '2026-06-26T13:00:00Z',
    invitedBy: 'user_012',
    permissions: getDefaultPermissions('requester'),
  },
  {
    id: 'user_014',
    orgId: 'org_003',
    email: 'abiodun.coker@oandoplc.com',
    displayName: 'Abiodun Coker',
    role: 'wh_supervisor',
    status: 'active',
    authProvider: 'email',
    department: 'Warehouse',
    jobTitle: 'Materials Coordinator',
    createdAt: '2025-02-05T09:00:00Z',
    lastActiveAt: '2026-06-27T05:30:00Z',
    invitedBy: 'user_012',
    permissions: getDefaultPermissions('wh_supervisor'),
  },

  // ── Lekoil Nigeria ────────────────────────────────────────────────────────
  {
    id: 'user_015',
    orgId: 'org_004',
    email: 'emeka.obi@lekoil.com.ng',
    displayName: 'Emeka Obi',
    role: 'org_admin',
    status: 'active',
    authProvider: 'email',
    department: 'Management',
    jobTitle: 'Country Operations Manager',
    createdAt: '2025-03-08T10:00:00Z',
    lastActiveAt: '2026-06-26T10:00:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_016',
    orgId: 'org_004',
    email: 'zainab.mohammed@lekoil.com.ng',
    displayName: 'Zainab Mohammed',
    role: 'requester',
    status: 'active',
    authProvider: 'email',
    department: 'Operations',
    jobTitle: 'Operations Coordinator',
    createdAt: '2025-03-10T09:00:00Z',
    lastActiveAt: '2026-06-24T14:00:00Z',
    invitedBy: 'user_015',
    permissions: getDefaultPermissions('requester'),
  },

  // ── Aiteo Eastern E&P ─────────────────────────────────────────────────────
  {
    id: 'user_017',
    orgId: 'org_005',
    email: 'peter.abah@aiteo.com.ng',
    displayName: 'Peter Abah',
    role: 'org_admin',
    status: 'active',
    authProvider: 'email',
    department: 'Management',
    jobTitle: 'Head of Operations',
    createdAt: '2026-06-20T08:00:00Z',
    lastActiveAt: '2026-06-27T07:00:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_018',
    orgId: 'org_005',
    email: 'grace.nnachi@aiteo.com.ng',
    displayName: 'Grace Nnachi',
    role: 'wh_supervisor',
    status: 'active',
    authProvider: 'email',
    department: 'Warehouse',
    jobTitle: 'Warehouse Lead',
    createdAt: '2026-06-21T09:00:00Z',
    lastActiveAt: '2026-06-26T16:00:00Z',
    invitedBy: 'user_017',
    permissions: getDefaultPermissions('wh_supervisor'),
  },
  {
    id: 'user_019',
    orgId: 'org_005',
    email: 'kola.akindele@aiteo.com.ng',
    displayName: 'Kola Akindele',
    role: 'requester',
    status: 'invited',
    authProvider: 'email',
    department: 'Engineering',
    jobTitle: 'Drilling Engineer',
    createdAt: '2026-06-23T10:00:00Z',
    invitedBy: 'user_017',
    permissions: getDefaultPermissions('requester'),
  },

  // ── Conoil ────────────────────────────────────────────────────────────────
  {
    id: 'user_020',
    orgId: 'org_006',
    email: 'ahmed.tijani@conoil.com.ng',
    displayName: 'Ahmed Tijani',
    role: 'org_admin',
    status: 'active',
    authProvider: 'email',
    department: 'Management',
    jobTitle: 'Logistics Director',
    createdAt: '2026-06-25T15:00:00Z',
    lastActiveAt: '2026-06-27T06:00:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_021',
    orgId: 'org_006',
    email: 'nkechi.obi@conoil.com.ng',
    displayName: 'Nkechi Obi',
    role: 'requester',
    status: 'invited',
    authProvider: 'email',
    department: 'Operations',
    createdAt: '2026-06-26T10:00:00Z',
    invitedBy: 'user_020',
    permissions: getDefaultPermissions('requester'),
  },

  // ── Waltersmith Petroman ──────────────────────────────────────────────────
  {
    id: 'user_022',
    orgId: 'org_007',
    email: 'joseph.walters@waltersmith.ng',
    displayName: 'Joseph Walters',
    role: 'org_admin',
    status: 'suspended',
    authProvider: 'email',
    department: 'Management',
    jobTitle: 'Operations Manager',
    createdAt: '2025-09-15T09:00:00Z',
    lastActiveAt: '2026-05-15T10:00:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },

  // ── Ardova Petroleum ──────────────────────────────────────────────────────
  {
    id: 'user_023',
    orgId: 'org_008',
    email: 'tokunbo.aromolaran@ardovapetroleum.com',
    displayName: 'Tokunbo Aromolaran',
    role: 'org_admin',
    status: 'active',
    authProvider: 'email',
    department: 'Management',
    jobTitle: 'VP Operations',
    createdAt: '2026-06-15T11:00:00Z',
    lastActiveAt: '2026-06-27T07:30:00Z',
    invitedBy: 'user_000',
    permissions: getDefaultPermissions('org_admin'),
  },
  {
    id: 'user_024',
    orgId: 'org_008',
    email: 'bimbo.adeyemi@ardovapetroleum.com',
    displayName: 'Adebimpe Adeyemi',
    role: 'requester',
    status: 'active',
    authProvider: 'email',
    department: 'Engineering',
    jobTitle: 'Petroleum Engineer',
    createdAt: '2026-06-16T09:00:00Z',
    lastActiveAt: '2026-06-26T15:30:00Z',
    invitedBy: 'user_023',
    permissions: getDefaultPermissions('requester'),
  },
]

/* ── Audit Events ─────────────────────────────────────────────────────────── */

export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'audit_001',
    orgId: null,
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'org.created',
    targetType: 'org',
    targetId: 'org_005',
    targetLabel: 'Aiteo Eastern E&P',
    metadata: { tier: 'professional', seats: 12 },
    ipAddress: '41.58.112.33',
    createdAt: '2026-06-20T08:10:00Z',
  },
  {
    id: 'audit_002',
    orgId: 'org_001',
    actorId: 'user_001',
    actorName: 'Chukwuemeka Nwosu',
    actorRole: 'org_admin',
    action: 'user.invited',
    targetType: 'user',
    targetId: 'user_007',
    targetLabel: 'yetunde.afolabi@shellnigeria.com',
    metadata: { role: 'dsp_personnel', department: 'Dispatch', authMethod: 'email' },
    ipAddress: '105.112.44.78',
    createdAt: '2026-06-22T11:30:00Z',
  },
  {
    id: 'audit_003',
    orgId: 'org_001',
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'sso.verified',
    targetType: 'sso',
    targetId: 'org_001',
    targetLabel: 'Shell Nigeria · Microsoft SSO',
    metadata: { tenantId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', provider: 'microsoft' },
    ipAddress: '41.58.112.33',
    createdAt: '2024-03-25T14:00:00Z',
  },
  {
    id: 'audit_004',
    orgId: 'org_007',
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'user.suspended',
    targetType: 'user',
    targetId: 'user_022',
    targetLabel: 'Joseph Walters',
    metadata: { reason: 'Org suspended due to payment failure' },
    ipAddress: '41.58.112.33',
    createdAt: '2026-06-02T09:00:00Z',
  },
  {
    id: 'audit_005',
    orgId: 'org_007',
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'org.suspended',
    targetType: 'org',
    targetId: 'org_007',
    targetLabel: 'Waltersmith Petroman',
    metadata: { reason: 'subscription_past_due', daysOverdue: 32 },
    ipAddress: '41.58.112.33',
    createdAt: '2026-06-02T09:05:00Z',
  },
  {
    id: 'audit_006',
    orgId: 'org_007',
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'subscription.past_due',
    targetType: 'subscription',
    targetId: 'org_007',
    targetLabel: 'Waltersmith Petroman · Starter Plan',
    metadata: { amount: 199, currency: 'USD', failureReason: 'card_declined' },
    ipAddress: '209.58.130.11',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'audit_007',
    orgId: null,
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'waitlist.approved',
    targetType: 'org',
    targetId: 'org_006',
    targetLabel: 'Conoil',
    metadata: { waitlistId: 'wl_001', tier: 'starter', trialDays: 30 },
    ipAddress: '41.58.112.33',
    createdAt: '2026-06-25T14:00:00Z',
  },
  {
    id: 'audit_008',
    orgId: 'org_005',
    actorId: 'user_017',
    actorName: 'Peter Abah',
    actorRole: 'org_admin',
    action: 'user.invited',
    targetType: 'user',
    targetId: 'user_019',
    targetLabel: 'kola.akindele@aiteo.com.ng',
    metadata: { role: 'requester', department: 'Engineering', authMethod: 'email' },
    ipAddress: '197.210.84.15',
    createdAt: '2026-06-23T10:05:00Z',
  },
  {
    id: 'audit_009',
    orgId: null,
    actorId: 'user_000',
    actorName: 'Aminu Garba',
    actorRole: 'sysadmin',
    action: 'org.created',
    targetType: 'org',
    targetId: 'org_008',
    targetLabel: 'Ardova Petroleum',
    metadata: { tier: 'professional', trialDays: 30, source: 'direct_signup' },
    ipAddress: '41.58.112.33',
    createdAt: '2026-06-15T11:05:00Z',
  },
  {
    id: 'audit_010',
    orgId: 'org_002',
    actorId: 'user_008',
    actorName: 'Olumide Akinwunmi',
    actorRole: 'org_admin',
    action: 'subscription.upgraded',
    targetType: 'subscription',
    targetId: 'org_002',
    targetLabel: 'Seplat Energy · Starter → Professional',
    metadata: { fromTier: 'starter', toTier: 'professional', newSeats: 20 },
    ipAddress: '196.207.56.12',
    createdAt: '2025-02-10T14:30:00Z',
  },
]

/* ── Invitations ──────────────────────────────────────────────────────────── */

export const INVITATIONS: Invitation[] = [
  {
    id: 'inv_001',
    orgId: 'org_001',
    email: 'ibrahim.bello@shellnigeria.com',
    role: 'wh_personnel',
    department: 'Warehouse',
    status: 'pending',
    token: 'tok-a1b2c3d4e5f6g7h8',
    invitedBy: 'user_003',
    expiresAt: '2026-07-04T00:00:00Z',
    authMethod: 'microsoft_sso',
  },
  {
    id: 'inv_002',
    orgId: 'org_002',
    email: 'chukwudi.onuoha@seplatpetroleum.com',
    role: 'dsp_supervisor',
    department: 'Dispatch',
    status: 'accepted',
    token: 'tok-b2c3d4e5f6g7h8i9',
    invitedBy: 'user_008',
    expiresAt: '2026-06-15T00:00:00Z',
    acceptedAt: '2026-06-12T14:00:00Z',
    authMethod: 'email',
  },
  {
    id: 'inv_003',
    orgId: 'org_003',
    email: 'florence.okeke@oandoplc.com',
    role: 'requester',
    department: 'Engineering',
    status: 'pending',
    token: 'tok-c3d4e5f6g7h8i9j0',
    invitedBy: 'user_012',
    expiresAt: '2026-07-06T00:00:00Z',
    authMethod: 'email',
  },
  {
    id: 'inv_004',
    orgId: 'org_001',
    email: 'michael.peters@shellnigeria.com',
    role: 'requester',
    status: 'expired',
    token: 'tok-d4e5f6g7h8i9j0k1',
    invitedBy: 'user_001',
    expiresAt: '2026-06-10T00:00:00Z',
    authMethod: 'microsoft_sso',
  },
  {
    id: 'inv_005',
    orgId: 'org_005',
    email: 'grace.nnachi@aiteo.com.ng',
    role: 'wh_supervisor',
    department: 'Warehouse',
    status: 'accepted',
    token: 'tok-e5f6g7h8i9j0k1l2',
    invitedBy: 'user_017',
    expiresAt: '2026-06-28T00:00:00Z',
    acceptedAt: '2026-06-21T09:15:00Z',
    authMethod: 'email',
  },
  {
    id: 'inv_006',
    orgId: 'org_005',
    email: 'bola.adedipe@aiteo.com.ng',
    role: 'dsp_supervisor',
    department: 'Dispatch',
    status: 'pending',
    token: 'tok-f6g7h8i9j0k1l2m3',
    invitedBy: 'user_017',
    expiresAt: '2026-07-05T00:00:00Z',
    authMethod: 'email',
  },
  {
    id: 'inv_007',
    orgId: 'org_004',
    email: 'ola.adeyemi@lekoil.com.ng',
    role: 'requester',
    status: 'expired',
    token: 'tok-g7h8i9j0k1l2m3n4',
    invitedBy: 'user_015',
    expiresAt: '2026-06-05T00:00:00Z',
    authMethod: 'email',
  },
  {
    id: 'inv_008',
    orgId: 'org_006',
    email: 'nkechi.obi@conoil.com.ng',
    role: 'requester',
    status: 'pending',
    token: 'tok-h8i9j0k1l2m3n4o5',
    invitedBy: 'user_020',
    expiresAt: '2026-07-10T00:00:00Z',
    authMethod: 'email',
  },
]

/* ── SSO Configurations ───────────────────────────────────────────────────── */

export const SSO_CONFIGS: SSOConfig[] = [
  {
    orgId: 'org_001',
    provider: 'microsoft',
    tenantId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    clientId: 'app-client-shell-001',
    status: 'verified',
    allowedDomains: ['shellnigeria.com', 'shell.com'],
    autoProvision: true,
    defaultRole: 'requester',
    verifiedAt: '2024-03-25T14:00:00Z',
  },
  {
    orgId: 'org_002',
    provider: 'microsoft',
    tenantId: 'b2c3d4e5-f6a7-8901-bcde-f01234567891',
    clientId: 'app-client-seplat-002',
    status: 'pending',
    allowedDomains: ['seplatpetroleum.com'],
    autoProvision: false,
    defaultRole: 'requester',
  },
]

/* ── Platform Stats ───────────────────────────────────────────────────────── */

export const PLATFORM_STATS: PlatformStats = {
  totalOrgs: 8,
  activeOrgs: 4,
  totalUsers: 25,
  activeUsers: 20,
  waitlistCount: 15,
  mrr: 4844,
  churnedThisMonth: 1,
  newOrgsThisMonth: 3,
  avgHealthScore: 61,
}
